name: Run CI checks

on: [pull_request]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

jobs:
  agents:
    name: Cloud Agents
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3, 4 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm install
      - name: Start Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  pr:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm install
      - name: Run Verification
        uses: JamesHenry/parallel-bash-commands@v0.1
        with:
          cmd1: npx nx build --parallel
          cmd2: npx nx test --parallel
          cmd3: npx nx lint --parallel
      - run: npx nx-cloud stop-all-agents
